/**
 * Dataverse Demo App - Main Application Component
 *
 * This app demonstrates how to use Power Apps code apps with Dataverse:
 * - CRUD operations (Create, Read, Update, Delete) on Contact and Account entities
 * - Lookup fields (linking Contacts to Accounts)
 * - File upload (AccountForm attachment sub-form)
 * - Error handling and best practices
 * - Component-based architecture
 *
 * ARCHITECTURE PATTERN:
 * ====================
 * The app follows a clean three-layer architecture:
 *
 * 1. COMPONENTS (Presentation Layer):
 *    - Pure presentational components (UI only, no business logic)
 *    - Receive data via props, emit events via callbacks
 *    - Examples: Header, ContactList, ContactForm, AccountList, AccountForm,
 *                ErrorMessage
 *
 * 2. HOOKS (Business Logic Layer):
 *    - Custom hooks that manage state and orchestrate services
 *    - Handle error handling, loading states, and data transformations
 *    - Examples: useContacts, useAccounts, useAccountsCrud, useLookupResolver
 *
 * 3. SERVICES (Data Access Layer):
 *    - Auto-generated by PAC CLI from Dataverse metadata
 *    - Handle all API communication with Dataverse
 *    - Examples: ContactsService, AccountsService, SystemusersService
 *
 * DATA FLOW:
 * ==========
 * User Action → Component → Hook → Service → Dataverse
 * Dataverse → Service → Hook → Component → UI Update
 *
 * This separation ensures:
 * - Testability: Each layer can be tested independently
 * - Maintainability: Changes to one layer don't cascade to others
 * - Reusability: Hooks and components can be reused across the app
 * - Clarity: Clear boundaries between presentation, logic, and data access
 */

import { useState } from 'react';
import {
  Header,
  ErrorMessage,
  ContactList,
  ContactForm,
  AccountList,
  AccountForm,
  Footer,
} from './components';
import { useContacts, useAccounts, useAccountsCrud } from './hooks';
import './App.css';

type ActivePage = 'contacts' | 'accounts';

function App() {
  const [activePage, setActivePage] = useState<ActivePage>('contacts');

  // PATTERN: Custom hooks handle all the business logic and state management
  // The component stays simple and focused on rendering UI
  const {
    contacts,
    loading: contactsLoading,
    error: contactsError,
    selectedContact,
    isCreating: isCreatingContact,
    startCreate: startCreateContact,
    selectContact,
    cancelForm: cancelContactForm,
    handleFormSubmit: handleContactFormSubmit,
    deleteContact,
  } = useContacts();

  // Load accounts for the Managing Partner lookup dropdown in the Contact form
  const { accounts } = useAccounts();

  // Full CRUD hook for the Accounts page
  const {
    accounts: accountsList,
    loading: accountsLoading,
    error: accountsError,
    selectedAccount,
    isCreating: isCreatingAccount,
    startCreate: startCreateAccount,
    selectAccount,
    cancelForm: cancelAccountForm,
    handleFormSubmit: handleAccountFormSubmit,
    deleteAccount,
    loadAccounts,
  } = useAccountsCrud();

  return (
    <div className="app-container">
      {/* Header Section */}
      <Header
        title="Dataverse Demo App"
        description="Demonstrating CRUD operations with Power Apps Code Apps"
      />

      {/* Page Navigation Tabs */}
      <nav className="page-tabs">
        <button
          className={`tab-btn ${activePage === 'contacts' ? 'active' : ''}`}
          onClick={() => setActivePage('contacts')}
        >
          Contacts
        </button>
        <button
          className={`tab-btn ${activePage === 'accounts' ? 'active' : ''}`}
          onClick={() => setActivePage('accounts')}
        >
          Accounts
        </button>
      </nav>

      {/* Contacts Page */}
      {activePage === 'contacts' && (
        <>
          <ErrorMessage error={contactsError} />
          <div className="content-grid">
            <ContactList
              contacts={contacts}
              selectedContact={selectedContact}
              loading={contactsLoading}
              onSelect={selectContact}
              onCreateNew={startCreateContact}
            />
            {(isCreatingContact || selectedContact) && (
              <ContactForm
                selectedContact={selectedContact}
                isCreating={isCreatingContact}
                accounts={accounts}
                onSubmit={handleContactFormSubmit}
                onCancel={cancelContactForm}
                onDelete={deleteContact}
              />
            )}
          </div>
        </>
      )}

      {/* Accounts Page */}
      {activePage === 'accounts' && (
        <>
          <ErrorMessage error={accountsError} />
          <div className="content-grid">
            <AccountList
              accounts={accountsList}
              selectedAccount={selectedAccount}
              loading={accountsLoading}
              onSelect={selectAccount}
              onCreateNew={startCreateAccount}
            />
            {(isCreatingAccount || selectedAccount) && (
              <AccountForm
                selectedAccount={selectedAccount}
                isCreating={isCreatingAccount}
                onSubmit={handleAccountFormSubmit}
                onCancel={cancelAccountForm}
                onDelete={deleteAccount}
                onUploadSuccess={loadAccounts}
              />
            )}
          </div>
        </>
      )}

      {/* Footer Section */}
      <Footer />
    </div>
  );
}

export default App;
