/**
 * Dataverse Demo App - Main Application Component
 *
 * This app demonstrates how to use Power Apps code apps with Dataverse:
 * - CRUD operations (Create, Read, Update, Delete) on Contact entities
 * - Lookup fields (linking Contacts to Accounts)
 * - Error handling and best practices
 * - Component-based architecture
 *
 * ARCHITECTURE PATTERN:
 * ====================
 * The app follows a clean three-layer architecture:
 *
 * 1. COMPONENTS (Presentation Layer):
 *    - Pure presentational components (UI only, no business logic)
 *    - Receive data via props, emit events via callbacks
 *    - Examples: Header, ContactList, ContactForm, ErrorMessage
 *
 * 2. HOOKS (Business Logic Layer):
 *    - Custom hooks that manage state and orchestrate services
 *    - Handle error handling, loading states, and data transformations
 *    - Examples: useContacts, useAccounts, useLookupResolver
 *
 * 3. SERVICES (Data Access Layer):
 *    - Auto-generated by PAC CLI from Dataverse metadata
 *    - Handle all API communication with Dataverse
 *    - Examples: ContactsService, AccountsService, SystemusersService
 *
 * DATA FLOW:
 * ==========
 * User Action → Component → Hook → Service → Dataverse
 * Dataverse → Service → Hook → Component → UI Update
 *
 * This separation ensures:
 * - Testability: Each layer can be tested independently
 * - Maintainability: Changes to one layer don't cascade to others
 * - Reusability: Hooks and components can be reused across the app
 * - Clarity: Clear boundaries between presentation, logic, and data access
 */

import {
  Header,
  ErrorMessage,
  ContactList,
  ContactForm,
  Footer,
} from "./components";
import { useContacts, useAccounts } from "./hooks";
import "./App.css";

function App() {
  // PATTERN: Custom hooks handle all the business logic and state management
  // The component stays simple and focused on rendering UI
  const {
    contacts,           // Array of contact records
    loading,            // Loading state for initial data fetch
    error,              // Error message string (null if no error)
    selectedContact,    // Currently selected contact for editing (null if none)
    isCreating,         // Flag indicating if we're in "create new" mode
    startCreate,        // Function to enter create mode
    selectContact,      // Function to select a contact for editing
    cancelForm,         // Function to cancel create/edit and return to list
    handleFormSubmit,   // Function to handle form submission (routes to create or update)
    deleteContact,      // Function to delete a contact
  } = useContacts();

  // Load accounts for the Managing Partner lookup dropdown
  const { accounts } = useAccounts();

  return (
    <div className="app-container">
      {/* Header Section */}
      <Header
        title="Dataverse Demo App"
        description="Demonstrating CRUD operations with Power Apps Code Apps"
      />

      {/* Error Display - Shows only when error exists */}
      <ErrorMessage error={error} />

      {/* Main Content Grid - Two column layout (list + form) */}
      <div className="content-grid">
        {/* Left Column: Contacts List */}
        <ContactList
          contacts={contacts}
          selectedContact={selectedContact}
          loading={loading}
          onSelect={selectContact}
          onCreateNew={startCreate}
        />

        {/* Right Column: Contact Form (shown only when creating or editing) */}
        {(isCreating || selectedContact) && (
          <ContactForm
            selectedContact={selectedContact}
            isCreating={isCreating}
            accounts={accounts}
            onSubmit={handleFormSubmit}
            onCancel={cancelForm}
            onDelete={deleteContact}
          />
        )}
      </div>

      {/* Footer Section */}
      <Footer />
    </div>
  );
}

export default App;
