/**
 * Dataverse Demo App - Main Application Component
 *
 * This app demonstrates how to use Power Apps code apps with Dataverse:
 * - CRUD operations (Create, Read, Update, Delete) on Contact and Account entities
 * - Lookup fields (linking Contacts to Accounts)
 * - File upload (AccountForm attachment sub-form)
 * - Error handling and best practices
 * - Component-based architecture
 *
 * ARCHITECTURE PATTERN:
 * ====================
 * The app follows a clean three-layer architecture:
 *
 * 1. COMPONENTS (Presentation Layer):
 *    - Pure presentational components (UI only, no business logic)
 *    - Receive data via props, emit events via callbacks
 *    - Examples: Header, ContactList, ContactForm, AccountList, AccountForm,
 *                ErrorMessage
 *
 * 2. HOOKS (Business Logic Layer):
 *    - Custom hooks that manage state and orchestrate services
 *    - Handle error handling, loading states, and data transformations
 *    - Examples: useContacts, useAccounts, useAccountsCrud, useLookupResolver
 *
 * 3. SERVICES (Data Access Layer):
 *    - Auto-generated by PAC CLI from Dataverse metadata
 *    - Handle all API communication with Dataverse
 *    - Examples: ContactsService, AccountsService, SystemusersService
 *
 * DATA FLOW:
 * ==========
 * User Action → Component → Hook → Service → Dataverse
 * Dataverse → Service → Hook → Component → UI Update
 *
 * This separation ensures:
 * - Testability: Each layer can be tested independently
 * - Maintainability: Changes to one layer don't cascade to others
 * - Reusability: Hooks and components can be reused across the app
 * - Clarity: Clear boundaries between presentation, logic, and data access
 */

import { useState } from 'react';
import {
  Header,
  ErrorMessage,
  ContactList,
  ContactForm,
  AccountList,
  AccountForm,
  ApiActionsPanel,
} from './components';
import { useContacts, useAccounts, useAccountsCrud, useCurrentUser } from './hooks';
import './App.css';

type ActivePage = 'contacts' | 'accounts' | 'apis';

function App() {
  const [activePage, setActivePage] = useState<ActivePage>('contacts');

  // PATTERN: Custom hooks handle all the business logic and state management
  // The component stays simple and focused on rendering UI
  const {
    contacts,
    loading: contactsLoading,
    error: contactsError,
    selectedContact,
    isCreating: isCreatingContact,
    startCreate: startCreateContact,
    selectContact,
    cancelForm: cancelContactForm,
    handleFormSubmit: handleContactFormSubmit,
    deleteContact,
  } = useContacts();

  // Load accounts for the Managing Partner lookup dropdown in the Contact form
  const { accounts } = useAccounts();

  // Full CRUD hook for the Accounts page
  const {
    accounts: accountsList,
    loading: accountsLoading,
    error: accountsError,
    selectedAccount,
    isCreating: isCreatingAccount,
    startCreate: startCreateAccount,
    selectAccount,
    cancelForm: cancelAccountForm,
    handleFormSubmit: handleAccountFormSubmit,
    deleteAccount,
    loadAccounts,
  } = useAccountsCrud();

  // Demonstrates Dataverse functions/actions support (WhoAmI)
  // API was added via: npx power-apps add-dataverse-api --api-name WhoAmI
  const { currentUser, loading: userLoading, error: userError } = useCurrentUser();

  return (
    <div className="app-container">
      {/* Header Section */}
      <Header
        title="Dataverse Demo App"
        description="Demonstrating the use of Dataverse with Power Apps Code Apps — CRUD, file storage, and custom APIs"
      />

      {/* Page Navigation Tabs */}
      <nav className="page-tabs">
        <button
          className={`tab-btn ${activePage === 'contacts' ? 'active' : ''}`}
          onClick={() => setActivePage('contacts')}
        >
          CRUD
        </button>
        <button
          className={`tab-btn ${activePage === 'accounts' ? 'active' : ''}`}
          onClick={() => setActivePage('accounts')}
        >
          File Attachments
        </button>
        <button
          className={`tab-btn ${activePage === 'apis' ? 'active' : ''}`}
          onClick={() => setActivePage('apis')}
        >
          Functions &amp; Actions
        </button>
      </nav>

      {/* CRUD Tab */}
      {activePage === 'contacts' && (
        <>
          <div className="tab-intro">
            <h3>CRUD Operations</h3>
            <p>
              Demonstrates <strong>Create</strong>, <strong>Read</strong>, <strong>Update</strong>,
              and <strong>Delete</strong> on Contact records using auto-generated services from{' '}
              <code>pac code add-data-source</code>. Lookup fields link contacts to accounts
              via OData bind syntax. Select a contact to edit, or create a new one.
            </p>
          </div>
          <ErrorMessage error={contactsError} />
          <div className="content-grid">
            <ContactList
              contacts={contacts}
              selectedContact={selectedContact}
              loading={contactsLoading}
              onSelect={selectContact}
              onCreateNew={startCreateContact}
            />
            {(isCreatingContact || selectedContact) && (
              <ContactForm
                selectedContact={selectedContact}
                isCreating={isCreatingContact}
                accounts={accounts}
                onSubmit={handleContactFormSubmit}
                onCancel={cancelContactForm}
                onDelete={deleteContact}
              />
            )}
          </div>
        </>
      )}

      {/* File Attachments Tab */}
      {activePage === 'accounts' && (
        <>
          <div className="tab-intro">
            <h3>Dataverse File Attachments</h3>
            <p>
              Demonstrates <strong>file upload</strong>, <strong>download</strong>, and{' '}
              <strong>delete</strong> on file and image columns using{' '}
              <code>AccountsService.upload()</code>, <code>downloadFile()</code>,{' '}
              <code>downloadImage()</code>, and <code>deleteFileOrImage()</code> — all generated
              by <code>pac code add-data-source</code>. Select an account and scroll to the
              Attachments section to try it.
            </p>
          </div>
          <ErrorMessage error={accountsError} />
          <div className="content-grid">
            <AccountList
              accounts={accountsList}
              selectedAccount={selectedAccount}
              loading={accountsLoading}
              onSelect={selectAccount}
              onCreateNew={startCreateAccount}
            />
            {(isCreatingAccount || selectedAccount) && (
              <AccountForm
                selectedAccount={selectedAccount}
                isCreating={isCreatingAccount}
                onSubmit={handleAccountFormSubmit}
                onCancel={cancelAccountForm}
                onDelete={deleteAccount}
                onUploadSuccess={loadAccounts}
              />
            )}
          </div>
        </>
      )}

      {/* Functions & Actions Tab */}
      {activePage === 'apis' && (
        <ApiActionsPanel
          currentUser={currentUser}
          loading={userLoading}
          error={userError}
        />
      )}

    </div>
  );
}

export default App;
