/**
 * useCurrentUser Hook
 * Calls the WhoAmI Dataverse function to identify the current user.
 *
 * The WhoAmIService was generated by running:
 *   npx power-apps find-dataverse-api --search "WhoAmI"
 *   npx power-apps add-dataverse-api --api-name WhoAmI
 *
 * Unlike CRUD services, Dataverse API services expose operation methods
 * (e.g. WhoAmIService.WhoAmI()) rather than create/get/update/delete.
 */

import { useState, useEffect } from 'react';
import { WhoAmIService } from '../generated/services/WhoAmIService';

export interface WhoAmIResult {
  BusinessUnitId: string;
  OrganizationId: string;
  UserId: string;
}

export function useCurrentUser() {
  const [currentUser, setCurrentUser] = useState<WhoAmIResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function fetchCurrentUser() {
      try {
        setLoading(true);
        setError(null);

        const result = await WhoAmIService.WhoAmI();

        if (!cancelled) {
          if (result.data) {
            setCurrentUser(result.data as unknown as WhoAmIResult);
          } else {
            setError('WhoAmI returned no data');
          }
        }
      } catch (err) {
        if (!cancelled) {
          setError(`Error calling WhoAmI: ${(err as Error).message}`);
          console.error('WhoAmI error:', err);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    fetchCurrentUser();
    return () => { cancelled = true; };
  }, []);

  return { currentUser, loading, error };
}
