/**
 * ApiActionsPanel — Dataverse Functions & Actions tab
 *
 * Demonstrates three patterns, each generated by:
 *   npx power-apps find-dataverse-api --search "<name>"
 *   npx power-apps add-dataverse-api --api-name <name>
 *
 * Pattern 1 — Unbound Function  : WhoAmI           (GET,  returns data)
 * Pattern 2 — Unbound Action    : SetAutoNumberSeed (POST, void)
 * Pattern 3 — Bound Action      : ConvertOwnerTeamToAccessTeam (POST, void, needs record ID)
 */

import type { WhoAmIResult } from '../hooks/useCurrentUser';

interface ApiActionsPanelProps {
  currentUser: WhoAmIResult | null;
  loading: boolean;
  error: string | null;
}

export function ApiActionsPanel({ currentUser, loading, error }: ApiActionsPanelProps) {
  return (
    <div className="apis-page">

      <div className="apis-intro">
        <p>
          Use <code>npx power-apps find-dataverse-api</code> to discover actions and functions
          in your environment, then <code>npx power-apps add-dataverse-api</code> to generate
          a typed service. These Dataverse API generators are not currently available via
          <code> pac </code>. Three patterns are shown below.
        </p>
      </div>

      {/* ── Card 1: Unbound Function ── */}
      <div className="api-entry">
        <div className="api-entry-meta">
          <span className="api-badge api-badge--function">Unbound Function</span>
          <h2 className="api-entry-name">WhoAmI</h2>
          <p className="api-entry-desc">
            Not bound to any table. Takes no parameters. Returns data — ideal for retrieving
            environment-level information.
          </p>
        </div>

        <div className="api-entry-body">
          <div className="api-section">
            <h4>Generated service</h4>
            <pre className="api-code"><code>{`// src/generated/services/WhoAmIService.ts
WhoAmIService.WhoAmI()
  : Promise<IOperationResult<Record<string, unknown>>>`}</code></pre>
          </div>

          <div className="api-section">
            <h4>Call</h4>
            <pre className="api-code"><code>{`const result = await WhoAmIService.WhoAmI();
const user = result.data; // WhoAmIResponse`}</code></pre>
          </div>

          <div className="api-section api-section--response">
            <h4>Response</h4>
            {loading && <p className="api-status">Calling WhoAmI...</p>}
            {error && <p className="api-error">{error}</p>}
            {currentUser && (
              <pre className="api-response-json"><code>{JSON.stringify(currentUser, null, 2)}</code></pre>
            )}
          </div>
        </div>
      </div>

      {/* ── Card 2: Unbound Action ── */}
      <div className="api-entry">
        <div className="api-entry-meta">
          <span className="api-badge api-badge--action">Unbound Action</span>
          <h2 className="api-entry-name">SetAutoNumberSeed</h2>
          <p className="api-entry-desc">
            Not bound to any table. Accepts typed scalar parameters.
            Performs a write operation — no data is returned.
          </p>
        </div>

        <div className="api-entry-body">
          <div className="api-section">
            <h4>Generated service</h4>
            <pre className="api-code"><code>{`// src/generated/services/SetAutoNumberSeedService.ts
SetAutoNumberSeedService.SetAutoNumberSeed(
  EntityName    : string,
  AttributeName : string,
  Value         : number
) : Promise<IOperationResult<void>>`}</code></pre>
          </div>

          <div className="api-section">
            <h4>Call</h4>
            <pre className="api-code"><code>{`const result = await SetAutoNumberSeedService
  .SetAutoNumberSeed("contact", "cr123_num", 1000);
// result.success === true on 204 No Content`}</code></pre>
          </div>

          <div className="api-section api-section--response">
            <h4>Response</h4>
            <pre className="api-response-json api-response-json--void"><code>void  // 204 No Content</code></pre>
          </div>
        </div>
      </div>

      {/* ── Card 3: Bound Action ── */}
      <div className="api-entry">
        <div className="api-entry-meta">
          <span className="api-badge api-badge--bound">Bound Action</span>
          <h2 className="api-entry-name">ConvertOwnerTeamToAccessTeam</h2>
          <p className="api-entry-desc">
            Bound to the <code>team</code> table. Operates on a specific record — the record
            GUID is passed as <code>id</code>. No data is returned.
          </p>
        </div>

        <div className="api-entry-body">
          <div className="api-section">
            <h4>Generated service</h4>
            <pre className="api-code"><code>{`// src/generated/services/ConvertOwnerTeamToAccessTeamService.ts
ConvertOwnerTeamToAccessTeamService
  .ConvertOwnerTeamToAccessTeam(
    id : string   // GUID of the team record
  ) : Promise<IOperationResult<void>>`}</code></pre>
          </div>

          <div className="api-section">
            <h4>Call</h4>
            <pre className="api-code"><code>{`const result = await ConvertOwnerTeamToAccessTeamService
  .ConvertOwnerTeamToAccessTeam(teamId);
// result.success === true on 204 No Content`}</code></pre>
          </div>

          <div className="api-section api-section--response">
            <h4>Response</h4>
            <pre className="api-response-json api-response-json--void"><code>void  // 204 No Content</code></pre>
          </div>
        </div>
      </div>

    </div>
  );
}
